library identifier: 'jenkins-shared-lib@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/ketanvj/jenkins-shared-lib.git'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                auditTools2 message: 'This is demo 2'
            }
        }
    }
}
